# application.yml
spring:
  application:
    name: carshop
  profiles:
    active: experiment

---


---
#experiment
spring:
  config:
    activate:
      on-profile: experiment

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

